#local environment
#server:
#  port: 8788

spring:
#  profiles: local
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/nim_perftest?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 12345678
    url: jdbc:mysql://106.2.90.25:3306/nim_perfdev?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://106.2.90.25:3306/nim_perftest?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: perf
    password: perftest
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 60000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  servlet:
    multipart:
#      location: E:\\
      max-file-size: 500MB
      max-request-size: 500MB

